# Generated by Django 2.1.5 on 2019-01-07 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FieldType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('widget_type', models.PositiveSmallIntegerField(choices=[(0, 'OneLineText'), (1, 'MultiLineText'), (2, 'Date'), (3, 'Enum')])),
                ('regex', models.CharField(max_length=3000)),
            ],
        ),
    ]
