language: python
python:
  - "3.6"
services:
  - docker
script:
  - docker-compose -f docker-compose.yml -f docker-compose.test.yml up -d
  - docker-compose exec web pipenv run bash -c 'pytest -s --cov=./'
  - >
    docker-compose exec
    spa bash -c '
      npm install &&
      npm run test:unit &&
      npm run test:e2e -- --config nightwatch.config.js --env headlessChrome
    '
